# Generated by Django 3.0.3 on 2020-02-10 01:42

import datetime, os
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def load_initial_data(apps, schema_editor):
    from django.contrib.auth.models import User
    Currency = apps.get_model('billing', 'Currency')

    for code in ['usd', 'cny', 'eur']:
        Currency.objects.create(code=code)

    user = User.objects.create_superuser('system',
        password=os.environ['SYSTEM_PASSWORD']
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator('0')])),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Transfer'), (1, 'Fee')], default=0)),
                ('source_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dest_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('dest_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_out', to='billing.Bill')),
                ('source_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_in', to='billing.Bill')),
            ],
            options={
                'db_table': 'billing_transaction',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Currency'),
        ),
        migrations.AddField(
            model_name='bill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.transactionbase',),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(amount__gte='0'), name='bill_balance_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('currency', 'owner')},
        ),
        migrations.RunPython(load_initial_data)
    ]
