version: "2.1"
services:
  data:
    image: busybox
    volumes:
      - ./:/app/

  web:
    image: nginx:alpine
    restart: always
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from: [data]
    links:
      - back
    networks:
      - net

  migrate:
    container_name: migrate
    build: .
    env_file:
      - .env
    volumes_from: [data]
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: ./manage.py migrate
    networks:
      - net

  back:
    container_name: back
    restart: always
    build: .
    env_file:
      - .env
    volumes_from: [data]
    links:
      - db
    networks:
      - net

  db:
    image: postgres:11-alpine
    restart: always
    container_name: db
    expose:
      - "5432"
    env_file:
        - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
    networks:
      - net

networks:
  net:
